name: CI
on:
  push:
    branches:
    - main
    - fix-windows
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  jvm-tests-1:
    timeout-minutes: 120
    runs-on: "windows-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: VirtusLab/scala-cli-setup@9bc68588ab2d49dae03e5395a5f411e20914f97e
      with:
        jvm: "temurin:17"
    - name: JVM integration tests
      run: ./mill -i integration.test "scala.cli.integration.PackageTestsDefault.native image"
      env:
        SCALA_CLI_IT_GROUP: 1
