name: CI
on:
  push:
    branches:
    - main
    - test-m1
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  generate-linux-arm64-native-launcher:
    runs-on: "macOS-m1"
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: VirtusLab/scala-cli-setup@9bc68588ab2d49dae03e5395a5f411e20914f97e
        with:
          apps: ""
      - name: Generate native launcher and generate os packages
        run: .github/scripts/build-linux-aarch64.sh
      - uses: actions/upload-artifact@v3
        with:
          name: linux-aarch64-launchers
          path: artifacts/
          if-no-files-found: error
          retention-days: 2
